version: 0.2
env:
  variables:
    S3_BUCKET: "ventas.logiiblue.com"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build: 
    commands:
      - echo Installing source NPM dependencies...
      - cd ventas-front
      - rm -rf node_modules
      - rm -rf dist
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - ng build -c qa
  post_build:
    commands:
      - aws s3 cp ./dist/ventas-front s3://$S3_BUCKET --recursive --acl public-read --cache-control "max-age=86400"
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: '*'
  discard-paths: yes
